[package]
name = "mzidentml"
version = "0.1.0"
edition = "2024"

exclude = [
    "/.github",
    "/test_files",
]

[dependencies]
bincode = { version = "2.0", features = ["serde"] }
chrono = "0.4.42"
context_error = "0.2.0"
mzcv = {version = "0.2.0", features = ["http"] }
quick-xml = { version = "0.38.4", features = ["serialize", "overlapped-lists"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_path_to_error = "0.1.20"
sha2 = "0.10.9"
thiserror = "2.0.17"
